services:
  mysql-server:
    image: mariadb:latest
    container_name: mysql-server
    restart: always
    environment:
      MARIADB_DATABASE: sharghal_db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql-server
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-server

volumes:
  mysql_data_container: